name: stride

description: Enables iterating Dart Lists and Iterables with a custom start index and step size (stride).

version: 0.0.1

homepage: https://github.com/simphotonics/stride

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  

dev_dependencies:
  benchmark: ^0.3.0
  pedantic: ^1.11.0
  test: ^1.17.5
