name: stride

description: Enables iterating Dart lists and iterables using a custom start
  index and step size (stride).

version: 1.1.0

homepage: https://github.com/simphotonics/stride

topics:
  - iterator
  - numerical-computation
  - stride
  - row-major
  - column-major

environment:
  sdk: '^3.0.0'

dependencies:
  exception_templates: ^0.3.1
  
dev_dependencies:
  benchmark_runner: ^0.1.4
  lints: ^3.0.0
  test: ^1.25.3
