name: stride

description: Enables iterating Dart lists and iterables using a custom start
  index and step size (stride).

version: 1.2.0

homepage: https://github.com/simphotonics/stride

topics:
  - iterator
  - numerical-computation
  - stride
  - row-major
  - column-major

environment:
  sdk: '^3.13.0'

dependencies:
  exception_templates: ^1.1.0

dev_dependencies:
  benchmark_runner: ^2.2.1
  lints: ^6.1.0
  test: ^1.32.0
