name: stride

description: Enables iterating Dart Lists and Iterables using a
  custom start index and step size (stride).

version: 1.0.0

homepage: https://github.com/simphotonics/stride

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  exception_templates: ^0.2.4

dev_dependencies:
  benchmark: ^0.3.0
  lints: ^2.0.1
  test: ^1.23.1
