name: stride

description: Generalized iterator and iterable that enable stepping through a
  Dart list with a custom stride and start index.

version: 0.0.1

homepage: https://github.com/simphotonics/stride

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
 
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.5
