name: stride

description: Provides the extension method
`stride` which returns an iterable with custom start index and step size.

version: 0.0.1

homepage: https://github.com/simphotonics/stride

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  exception_templates: ^0.2.1

dev_dependencies:
  benchmark: ^0.3.0
  pedantic: ^1.11.0
  test: ^1.17.5
